name: Ficker Front Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - pull_request

env:
  GCP_ADDRESS: us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan
  GHCR_IMAGE: ghcr.io/alandysson/ficker-front:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: docker buildx build -t ghcr.io/alandysson/ficker-front:latest --push .

  tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      image: ghcr.io/alandysson/ficker-front:latest

    steps:
      - name: Run the image
        run: |
          docker run -d -p 3000:3000 $GHCR_IMAGE --name ficker-front
          sleep 5

      - name: Run tests
        run: |
          docker exec $(docker ps -q) yarn test
          docker exec $(docker ps -q) cat reports/jest-junit.xml | tee /tmp/jest-junit.xml

      - name: Copy Test Results
        if: always()
        run: |
          cp -Lpr /tmp/jest-junit.xml test-results.xml
        shell: bash

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            test-results.xml

  deploy-to-registry:
    runs-on: ubuntu-latest
    services:
      image: ghcr.io/alandysson/ficker-front:latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag the image to publish
        run: docker tag $GHCR_IMAGE $GCP_ADDRESS:latest

      - name: Login into gcp
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Use gcloud CLI
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin $GCP_ADDRESS

      - name: Push the image to GCP
        run: docker push $GCP_ADDRESS:latest

  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    needs: deploy-to-registry
    steps:
      - name: Login to gcp
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "alan"
          image: "us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:latest"
