name: Ficker Front Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  # build:
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to GitHub Container Registry
  #     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #   - name: Build and push
  #     run: |
  #       docker buildx build -t ghcr.io/alandysson/ficker-front:latest --push .
  use:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ghcr.io/alandysson/ficker-front:latest
          path: ghcr.io/alandysson/
      - name: Load image
        run: |
          docker load --input /ghcr.io/alandysson/ficker-front:latest.tar
          docker image ls -a

  test:
    runs-on: ubuntu-latest
    container: ghcr.io/alandysson/ficker-front:latest
    needs: use
    steps:
      - name: Run the image
        run: docker -v

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results
  # - name: Push image
  #   run: docker buildx build -t ${{ env.GAR_LOCATION }} --push .

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: Pull image
  #       run: docker pull ghcr.io/alandysson/ficker-front:latest

  #     - name: Tag image
  #       run: docker tag ghcr.io/alandysson/ficker-front:latest us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:latest

  #     - name: Login to gcp
  #       uses: "google-github-actions/auth@v2"
  #       with:
  #         credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

  #     - name: "Set up Cloud SDK"
  #       uses: "google-github-actions/setup-gcloud@v2"
  #       with:
  #         version: ">= 363.0.0"

  #     - name: "Use gcloud CLI"
  #       run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan

  #     - name: Push to GCP
  #       run: |
  #         docker push us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:latest

  # cloudRun:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - name: Login to gcp
  #       uses: "google-github-actions/auth@v2"
  #       with:
  #         credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

  #     - name: "Set up Cloud SDK"
  #       uses: "google-github-actions/setup-gcloud@v2"
  #       with:
  #         version: ">= 363.0.0"

  #     - name: Deploy to Cloud Run
  #       uses: "google-github-actions/deploy-cloudrun@v2"
  #       with:
  #         service: "alan"
  #         image: "us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:latest"
  #         port: 3000
