name: Ficker Front Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v4

  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v3

  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v3

  #       - name: Login to GitHub Container Registry
  #         run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #       - name: Build and push
  #         run: |
  #           docker buildx build -t ghcr.io/alandysson/ficker-front:latest --push .

  test:
    runs-on: ubuntu-latest
    container: ghcr.io/alandysson/ficker-front:latest
    # needs: build
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Run Jest tests
        run: npm test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results


      # - name: Push image
      #   run: docker buildx build -t ${{ env.GAR_LOCATION }} --push .
